services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: local
      VITE_APP_URL: http://localhost:8000
      VITE_SERVER_HOST: http://localhost:5173
    volumes:
      - ./:/var/www/html
      - ./.env.local:/var/www/html/.env
    env_file:
      - .env.local
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: toolbox
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - '8082:80'
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=secret
      - UPLOAD_LIMIT=300M
    depends_on:
      - db
    networks:
      - laravel

  vite:
    image: node:18
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - node_modules:/var/www/html/node_modules
    ports:
      - '5173:5173'
    command: sh -c "npm install && npm run dev"
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - VITE_APP_URL=http://localhost:8000
    networks:
      - laravel

networks:
  laravel:
  openldap:
    driver: bridge
    name: laravel_ldap

volumes:
  mysql_data:
  ldap_data:
  node_modules:
