services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: local
      VITE_APP_URL: http://localhost:8000
      VITE_SERVER_HOST: http://localhost:5173
    volumes:
      - ./:/var/www/html
      - ./.env.local:/var/www/html/.env
    env_file:
      - .env.local
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: toolbox
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - '8082:80'
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=secret
      - UPLOAD_LIMIT=300M
    depends_on:
      - db
    networks:
      - laravel

  vite:
    image: node:18
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - node_modules:/var/www/html/node_modules
    ports:
      - '5173:5173'
    command: sh -c "npm install && npm run dev"
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - VITE_APP_URL=http://localhost:8000
    networks:
      - laravel

  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: openldap
    ports:
      - '389:389'
    volumes:
      - ./openldap-data/slapd/database:/var/lib/ldap
      - ./openldap-data/slapd/config:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=SPSE
      - LDAP_DOMAIN=spse.local
      - LDAP_BASE_DN=dc=spse,dc=local
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_PASSWORD=config_pass
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=user-ro
      - LDAP_READONLY_USER_PASSWORD=ro_pass
    networks:
      - openldap
      - laravel

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports:
      - '8081:80'
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - openldap
      - laravel

networks:
  laravel:
  openldap:
    driver: bridge
    name: laravel_ldap

volumes:
  mysql_data:
  ldap_data:
  node_modules:
